version: '3.9'

services:

  mongo:
    container_name: container-mongodb
    image: mongo
    restart: always
    volumes:
      - .docker/db-mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - network_sport_news

  api:
    container_name: container-api
    image: api
    environment:
      - PROFILE=dev
    build:
      context: ./api-sport-news
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    entrypoint: /opt/bin/entrypoint.sh
    depends_on:
      - mongo
    networks:
      - network_sport_news

volumes:
  .docker:

networks:
  network_sport_news: { }