version: '3.9'

services:

  mongo:
    container_name: container-mongodb
    image: mongo
    restart: always
    volumes:
      - .docker/db-mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - network_sport_news
      
  rabbitmq:
    container_name: container-rabbitmq
    image: 'rabbitmq:3.12.1-management-alpine'
    ports:
      - "5672:5672" # The standard AMQP protocol port
      - "15672:15672" # HTTP management UI
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    networks:
      - network_sport_news
      
  api:
    container_name: container-api
    image: api
    environment:
      - PROFILE=dev
    build:
      context: ./api-sport-news
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    entrypoint: /opt/bin/entrypoint.sh
    depends_on:
      - mongo
    networks:
      - network_sport_news
      
volumes:
  .docker:

networks:
  network_sport_news: { }