version: '3.1'

services:

  mongo:
    container_name: container-mongodb
    image: mongo
    restart: always
    volumes:
      - .docker/db-mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - network_sport_news
      
volumes:
  .docker:

networks:
  network_sport_news: { }